language: node_js
node_js:
- '8'
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    repo: RockaLabs/search-text-highlight
    tags: true
    branch: master